import { MIN_PASSWORD_LENGTH, PIN_LENGTH } from "../shared/auth";
import {
  MAX_BREAK_MINUTES,
  MAX_QUIZ_ATTEMPTS_LIMIT,
  MAX_RE_EXPLANATIONS_LIMIT,
  type AccentColor,
  type AvatarId,
  type GoalKind,
  type GoalStatus,
  type PathState,
} from "../shared/api";
import type { LlmErrorKind } from "../shared/llm";

/** The Tutor's name, in the UI only: in the domain and the code it is the Tutor. */
const TUTOR_NAME = "Jarvis";
const pinDigits =`${PIN_LENGTH.min} to ${PIN_LENGTH.max} digits`;

/** What the Learner sees instead of a Tutor reply once the Parent's daily token cap is reached. */
const DAILY_LIMIT = "That's enough for today! You've worked really hard. Come back tomorrow to carry on.";
const LESSON_UNAVAILABLE = "This Lesson can't be taught just now. Ask your Parent to check the Curriculum in the Parent area.";

/** A YYYY-MM-DD date as e.g. "Tue, Oct 20". Read as a local day so it never shifts across time zones. */
function formatDate(date: string): string {
  const [year, month, day] = date.split("-").map(Number);
  return new Date(year!, month! - 1, day).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
}

/** A Lesson or Unit key as the Parent's Goal table shows it, e.g. "math/term-1/unit-2/lesson-3" as "1.2.3"; any other key as it is. */
function shortKey(key: string): string {
  const numbers = key.match(/^[^/]+\/term-(\d+)\/unit-(\d+)(?:\/lesson-(\d+))?$/);
  return numbers ? numbers.slice(1).filter(Boolean).join(".") : key;
}

/** All UI text, in one place for later translation (English only in v1). */
export const text = {
  appName: "Home Tutor",
  /** A Goal's title as shown everywhere: a Unit Test's is its Unit's, so it says what it is. */
  goalTitle: (kind: GoalKind, title: string) => (kind === "unit-test" ? `Unit Test: ${title}` : title),
  loading: "Loading…",
  genericError: "Something went wrong. Please try again.",
  setup: {
    heading: "Welcome to Home Tutor",
    intro: "Set a Parent password. You'll need it to reach the Parent area, so your children can't.",
    passwordLabel: "Parent password",
    confirmLabel: "Confirm password",
    hint: `At least ${MIN_PASSWORD_LENGTH} characters.`,
    tooShort: `The password must be at least ${MIN_PASSWORD_LENGTH} characters.`,
    mismatch: "The passwords don't match.",
    submit: "Set password",
  },
  login: {
    heading: "Parent login",
    passwordLabel: "Parent password",
    wrongPassword: "That password isn't right.",
    submit: "Log in",
    back: "Back",
  },
  learnerLogin: {
    heading: "Who's learning today?",
    intro: "Tap your name to pick up where you left off.",
    hasPin: "PIN",
    noProfiles: "No Learners yet. Ask your Parent to add you in the Parent area.",
    parentLink: "Parent area",
    pinHeading: (name: string) => `Hi ${name}! Enter your PIN.`,
    pinLabel: "PIN",
    wrongPin: "That PIN isn't right. Try again.",
    submit: "Start",
    back: "Back",
  },
  /** Each Avatar picture's name, read out for the picture grid. */
  avatars: {
    fox: "Fox",
    owl: "Owl",
    cat: "Cat",
    panda: "Panda",
    frog: "Frog",
    whale: "Whale",
    penguin: "Penguin",
    turtle: "Turtle",
    rocket: "Rocket",
    planet: "Planet",
    bolt: "Lightning bolt",
    mountain: "Mountain",
    cactus: "Cactus",
    guitar: "Guitar",
    controller: "Game controller",
    leaf: "Leaf",
  } satisfies Record<AvatarId, string>,
  /** Each accent colour's name, read out for the colour swatches. */
  colors: {
    coral: "Coral",
    amber: "Amber",
    sun: "Sunshine",
    mint: "Mint",
    sky: "Sky",
    indigo: "Indigo",
    violet: "Violet",
    pink: "Pink",
  } satisfies Record<AccentColor, string>,
  avatarPick: {
    eyebrow: "Set up",
    heading: (name: string) => `Make it yours, ${name}.`,
    intro: "Pick a picture and a colour. You can ask your Parent to change them later.",
    pictureHeading: "Picture",
    colorHeading: "Colour",
    done: "Done",
    notMe: (name: string) => `Not ${name}? Switch profile`,
  },
  learnerHome: {
    heading: (name: string) => `Hi ${name}!`,
    noGoals: "There's nothing to work on yet. Your Parent will set your first Goal soon.",
    target: (date: string) => `Aim to finish by ${formatDate(date)}`,
    catchUp: "This one's waiting for you. Let's catch up!",
    catchUpTag: "Catch up",
    continue: `Continue with ${TUTOR_NAME}`,
    continueEyebrow: (subjectName: string, termName: string | undefined) => (termName ? `${subjectName} · ${termName}` : subjectName),
    allSubjects: "All subjects",
    /** Neutral on purpose: a Flagged or Orphaned Goal isn't the Learner's fault. */
    withParent: "With your Parent for now",
    allDone: "All done for now",
    nothingNow: "Nothing to start just now. Your Parent will set up what comes next.",
    termProgress: (met: number, total: number) => `${met}/${total}`,
    termProgressLabel: (subjectName: string, termName: string, met: number, total: number) =>
      `${subjectName} ${termName}: ${met} of ${total} Goals met`,
    goalsMet: "Goals met",
    start: "Start",
  },
  learningPath: {
    unit: (n: number) => `Unit ${n}`,
    lesson: (unit: number, n: number) => `Lesson ${unit}.${n}`,
    unitTest: "Unit Test",
    /** What each state says beside a node, and in the legend; the current node has its Start button instead. */
    states: { met: "Done", current: "Up next", skipped: "Skipped", "with-parent": "With your Parent", ahead: "Later" } satisfies Record<PathState, string>,
    legendLabel: "What the marks mean",
    ring: (met: number, total: number) => `${met} of ${total} done this Term`,
    ringOf: (total: number) => `of ${total}`,
    noPath: "Your Learning Path shows up here once your Parent sets a Goal in this Subject.",
  },
  learnerNav: {
    today: "Today",
    learningPath: "Learning Path",
    switchProfile: "Switch profile",
  },
  session: {
    back: "Back to Today",
    leave: "Leave",
    tutor: TUTOR_NAME,
    you: "You",
    writing: "is writing…",
    steps: {
      lesson: ["Explanation", "Check you've got it", "Lesson Quiz"],
      "unit-test": ["Unit Test"],
    } satisfies Record<GoalKind, string[]>,
    stepsLabel: "Steps",
    stepDone: "(done)",
    objectivesHeading: "You'll be able to",
    conversationLabel: "Conversation",
    messageLabel: "Your answer",
    messagePlaceholder: "Write your answer…",
    send: "Send",
    failed: `${TUTOR_NAME} couldn't reply just then.`,
    retry: "Try again",
    ended: "That's all for this Lesson today. Your Parent will help you with it next.",
    lessonUnavailable: LESSON_UNAVAILABLE,
    dailyLimit: DAILY_LIMIT,
    breakHeading: (minutes: number) => `${minutes} minutes in. Time for a short break?`,
    breakHint: "Stretch, get a drink, then come back. Your place is saved.",
    keepGoing: "Keep going",
    takeBreak: "Take a break",
    quizReady: { lesson: "Ready for the Lesson Quiz?", "unit-test": "Ready for the Unit Test?" } satisfies Record<GoalKind, string>,
    quizReadyHint: {
      lesson: "One question at a time, so take your time.",
      "unit-test": "It covers every Lesson in this Unit, one question at a time.",
    } satisfies Record<GoalKind, string>,
  },
  quiz: {
    heading: { lesson: "Lesson Quiz", "unit-test": "Unit Test" } satisfies Record<GoalKind, string>,
    attempt: (number: number, max: number) => `Quiz ${number} of ${max}`,
    start: "Start the Quiz",
    startAgain: "Start the new Quiz",
    writing: `${TUTOR_NAME} is writing your quiz…`,
    question: (n: number, total: number) => `Question ${n} of ${total}`,
    topTitle: (kind: GoalKind, title: string, attempt: number, maxAttempts: number) =>
      `${kind === "unit-test" ? "Unit Test" : "Lesson Quiz"} · ${title} · Quiz ${attempt} of ${maxAttempts}`,
    numberPlaceholder: "0",
    outOf: (total: number) => `/${total}`,
    progress: (right: number, wrong: number, total: number) => `${right} right and ${wrong} not quite, of ${total} questions`,
    numberLabel: "Your answer",
    numberHint: "A number, like 12, 0.5 or 3/4.",
    writtenLabel: "Your answer",
    writtenPlaceholder: "Explain in a sentence or two",
    submit: "Check",
    checking: "Checking…",
    right: "Correct.",
    wrong: "Not quite.",
    correctAnswer: (answer: string) => `Answer: ${answer}`,
    next: "Continue",
    score: (correct: number, total: number) => `You got ${correct} out of ${total} right.`,
    choicesLabel: "Choose an answer",
    rightChoice: "(the right answer)",
    markedRight: "Right:",
    markedWrong: "Not quite:",
    reTeachHeading: "Let's look again at the parts you missed.",
    reTeachHint: `${TUTOR_NAME} will go over these with you, then you'll get a new quiz.`,
    goOver: `Go over it with ${TUTOR_NAME}`,
    ended: "You worked really hard on this quiz. That's all for today, and your Parent will help you with it next.",
    failed: `${TUTOR_NAME} couldn't do that just then.`,
    errors: {
      invalidAnswer: "Choose one of the answers, or for a number question, type a number.",
      answerRequired: "Type your answer first.",
      dailyLimitReached: DAILY_LIMIT,
      lessonUnavailable: LESSON_UNAVAILABLE,
    } as Record<string, string>,
  },
  goalMet: {
    eyebrow: (subjectName: string) => `Goal met · ${subjectName}`,
    scoreLine: { lesson: "on the Lesson Quiz.", "unit-test": "on the Unit Test." } satisfies Record<GoalKind, string>,
    score: (correct: number, total: number, on: string) => `${correct} of ${total} ${on} ${TUTOR_NAME} is proud of you!`,
    goalsMet: "Goals met",
    thisTerm: (subjectName: string, termName: string) => `${subjectName} ${termName}`,
    upNext: "Up next",
    when: (subjectName: string, targetDate: string) => `${subjectName} · Aim to finish by ${formatDate(targetDate)}`,
    start: "Start",
  },
  teachingSettings: {
    heading: "Teaching",
    maxReExplanationsLabel: "Re-explanations before a Goal is flagged",
    hint: "When the Tutor has re-explained this many times and the Learner still doesn't understand, the Goal is handed back to you as a Flagged Goal.",
    passMarkLabel: "Pass mark (%)",
    passMarkHint: "The share of a Lesson Quiz's answers that must be right for the Goal to be met.",
    maxQuizAttemptsLabel: "Quiz attempts before a Goal is flagged",
    maxQuizAttemptsHint: "After this many attempts below the pass mark, the Goal is handed back to you as a Flagged Goal.",
    save: "Save",
    saved: "Saved.",
    errors: {
      invalidMaxReExplanations: `Re-explanations must be a whole number from 0 to ${MAX_RE_EXPLANATIONS_LIMIT}.`,
      invalidPassMark: "The pass mark must be a whole number from 1 to 100.",
      invalidMaxQuizAttempts: `Quiz attempts must be a whole number from 1 to ${MAX_QUIZ_ATTEMPTS_LIMIT}.`,
    } as Record<string, string>,
  },
  goals: {
    heading: "Goals",
    none: "No Goals yet. Set one below.",
    noneNeedAttention: "Nothing needs your attention.",
    filterLabel: "Which Goals",
    filterAll: "All",
    filterAttention: (count: number) => `Needs attention · ${count}`,
    columns: { lesson: "Lesson", goal: "Goal", target: "Target", status: "Status", actions: "Actions" },
    shortKey,
    targetDate: formatDate,
    daysLate: (days: number) => `${days} ${days === 1 ? "day" : "days"} late`,
    status: { active: "Active", met: "Met", flagged: "Flagged", skipped: "Skipped" } satisfies Record<GoalStatus, string>,
    orphaned: "Lesson no longer in the Curriculum",
    review: "Review",
    change: "Change",
    flaggedHint: `${TUTOR_NAME} handed this Goal back to you. Retry it for a fresh Session, mark it met if you taught it yourself, or skip it.`,
    addHeading: "Set a Goal",
    orphanedHint: "This Goal's Lesson was renumbered or removed. Re-point it to a Lesson, or remove it. Until then the Learner sees this Subject is with you, with nothing to start.",
    retry: "Retry",
    markMet: "Mark met",
    repointLabel: (title: string) => `New Lesson for ${title}`,
    repoint: "Re-point",
    remove: "Remove",
    confirmRemove: (title: string) => `Remove the Goal "${title}"? Its Sessions and transcripts will be deleted too.`,
    lessonLabel: "Lesson",
    lessonOption: (unitTitle: string, title: string) => `${unitTitle} · ${title}`,
    targetDateLabel: "Target Date",
    add: "Set Goal",
    positionLabel: "Place in queue",
    atEnd: "At the end",
    before: (title: string) => `Before ${title}`,
    editTargetDate: (title: string) => `Target Date for ${title}`,
    moveUp: "Move up",
    moveDown: "Move down",
    skip: "Skip",
    spreadHeading: "Spread Target Dates over a Term",
    spreadHint:
      "Target Dates are spread evenly from today to the Term end date across the Term's Lessons still to be met. Lessons without a Goal get one.",
    termLabel: "Term",
    termOption: (subjectName: string, termName: string) => `${subjectName} · ${termName}`,
    termEndDateLabel: "Term end date",
    spread: "Spread Target Dates",
    noLessons: "This Learner's Curriculum has no Lessons to choose from. Check it's valid in the Curricula list.",
    errors: {
      unknownLesson: "Choose a Lesson from this Learner's Curriculum.",
      invalidTargetDate: "Choose a Target Date.",
      invalidPosition: "Choose a place in the same Subject's queue.",
      lessonHasGoal: "This Lesson already has a Goal still to be met.",
      unknownTerm: "Choose a Term from this Learner's Curriculum.",
      invalidTermEndDate: "Choose a Term end date.",
      termEndDatePassed: "The Term end date can't be in the past.",
      goalNotActive: "Only a Goal still to be met can be skipped.",
      goalNotFlagged: "This Goal isn't flagged any more.",
      goalNotOrphaned: "This Goal's Lesson is in the Curriculum, so it can't be re-pointed or removed. Skip it instead.",
      lessonUnavailable: "This Goal's Lesson isn't in the Curriculum, so it can't be marked met.",
      invalidOrder: "The Goals changed meanwhile. Try again.",
    } as Record<string, string>,
  },
  parentArea: {
    heading: "Parent area",
    logout: "Log out",
    nav: { learners: "Learners", curricula: "Curricula", settings: "Settings", usage: "Usage" },
  },
  learners: {
    heading: "Learners",
    none: "No Learners yet. Add one below.",
    details: (grade: string, curriculumId: string, hasPin: boolean) =>
      `Grade ${grade} · ${curriculumId}${hasPin ? " · PIN set" : ""}`,
    grade: (grade: string) => `Grade ${grade}`,
    needsAttention: (count: number) => `${count} ${count === 1 ? "Goal needs" : "Goals need"} attention`,
    views: { goals: "Goals", progress: "Progress" },
    viewsLabel: "Learner views",
    removeLearner: (name: string) => `Remove ${name}`,
    addHeading: "Add a Learner",
    editHeading: (name: string) => `Edit ${name}`,
    nameLabel: "Name",
    gradeLabel: "Grade",
    curriculumLabel: "Curriculum",
    noValidCurricula: "Add a valid Curriculum before adding Learners.",
    pinLabel: "PIN (optional)",
    pinHint: `${pinDigits}. Leave empty for no PIN.`,
    newPinLabel: "New PIN",
    newPinHint: `${pinDigits}. Leave empty to keep the current PIN.`,
    removePin: "Remove the PIN",
    avatarLabel: "Avatar",
    noAvatar: "None yet (picked at the next login)",
    colorLabel: "Colour",
    add: "Add Learner",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    remove: "Remove",
    confirmRemove: (name: string) => `Remove ${name}? Their progress will be deleted too.`,
    errors: {
      nameRequired: "Enter a name.",
      gradeRequired: "Enter a grade.",
      unknownCurriculum: "Choose a valid Curriculum.",
      invalidPin: `A PIN is ${pinDigits}.`,
      unknownAvatar: "Choose one of the Avatars.",
      unknownColor: "Choose one of the colours.",
    } as Record<string, string>,
  },
  llmSettings: {
    heading: "Tutor model",
    intro: "The Tutor uses your own API key, which you set as an environment variable. It is never stored by Home Tutor.",
    providerLabel: "Provider",
    modelLabel: "Model",
    keyHint: (envVar: string) => `Set your key in the ${envVar} environment variable, then restart Home Tutor.`,
    save: "Save",
    saved: "Saved.",
    test: "Test connection",
    testing: "Testing…",
    ok: "Connected. The Tutor is ready.",
    errors: {
      modelRequired: "Enter a model.",
      unknownProvider: "Choose a provider.",
    } as Record<string, string>,
    testErrors: {
      missingKey: (envVar: string) => `No API key found. Set ${envVar} and restart Home Tutor.`,
      rejectedKey: (envVar: string) => `The provider rejected the key in ${envVar}. Check that it's correct and active.`,
      unknownModel: (_envVar: string, model: string) => `The provider doesn't recognise the model "${model}". Check its name.`,
      failed: () => "Couldn't reach the provider. Check your internet connection and try again.",
    } satisfies Record<LlmErrorKind, (envVar: string, model: string) => string>,
  },
  progress: {
    summary: { met: "Met", overdue: "Overdue", flagged: "Flagged", orphaned: "Missing Lesson" },
    summaryLabel: "Goals at a glance",
    noGoals: "No Goals yet, so no progress to show.",
    noSessions: "No Sessions yet.",
    transcriptLabel: "Transcript",
    session: (startedAt: string, open: boolean) => `Session on ${new Date(startedAt).toLocaleString()}${open ? " (open)" : ""}`,
    attempt: (number: number, correct: number, total: number, passed: boolean) =>
      `Quiz ${number}: ${correct} out of ${total}${passed ? " (passed)" : ""}`,
    readTranscript: "Read transcript",
    closeTranscript: "Close transcript",
    noMessages: "No messages yet.",
    quizHeading: (number: number) => `Quiz ${number}`,
    question: (n: number, prompt: string) => `${n}. ${prompt}`,
    answer: (answer: string | null, correct: boolean | null, answerKey: string) =>
      answer === null ? `Not answered yet (answer: ${answerKey})` : `Answered "${answer}": ${correct ? "right" : `wrong (answer: ${answerKey})`}`,
  },
  limitSettings: {
    heading: "Limits",
    dailyTokenCapLabel: "Daily token cap",
    dailyTokenCapHint: "The most tokens the Tutor may use in a day. Once reached, the Learner is told that's enough for today. Leave empty for no cap.",
    breakMinutesLabel: "Break prompt after (minutes)",
    breakMinutesHint: "How long into a sitting the Learner is prompted to take a break.",
    save: "Save",
    saved: "Saved.",
    errors: {
      invalidDailyTokenCap: "The daily token cap must be a whole number above 0, or empty for no cap.",
      invalidBreakMinutes: `The break prompt time must be a whole number of minutes from 1 to ${MAX_BREAK_MINUTES}.`,
    } as Record<string, string>,
  },
  usage: {
    heading: "Token usage",
    none: "No tokens used yet.",
    day: (date: string, calls: number, input: number, output: number) =>
      `${date}: ${input.toLocaleString()} in, ${output.toLocaleString()} out (${calls} ${calls === 1 ? "call" : "calls"})`,
  },
  curricula: {
    heading: "Curricula",
    none: "No Curriculum folders found. Add one to the curricula folder (see docs/curriculum-format.md).",
    details: (district: string, grade: string, schoolYear: string) => `${district} · Grade ${grade} · ${schoolYear}`,
    subject: (name: string, lessons: number) => `${name}: ${lessons} ${lessons === 1 ? "Lesson" : "Lessons"}`,
    invalid: (count: number) =>
      `This Curriculum has ${count} ${count === 1 ? "error" : "errors"} and can't be used for teaching until it's fixed. Run npm run curriculum:check for the same list.`,
    location: (file: string, line?: number) => (line === undefined ? file : `${file}:${line}`),
  },
} as const;
